# Generated by Django 5.0.6 on 2024-07-27 17:47

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("22fca2f8-3769-4313-913c-0cd3321f2766"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="displacedproduct",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("8597460c-9952-49b9-b702-920db9aba9f5"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("81fc2847-c2b6-4e55-9689-5d057665ded3"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="ordersdeatails",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("d2a0447c-5a7e-4bb8-b0c8-5260714a8942"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("276cb4b1-e6cc-4040-8e9c-d00fa632e1b4"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("dbc7e0b1-d97d-4b34-9a79-e62273160561"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("dd2f2439-63bd-46e4-9b56-4879c2bdf49d"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
