# Generated by Django 5.0.6 on 2024-07-27 18:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_app_id_alter_displacedproduct_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("d42f9f6f-86dd-433f-bbca-ecc91d251d6b"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="displacedproduct",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("9fe5a1f1-5979-4a84-98a2-5b3be29c7f90"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("1e99dd4c-b76d-4d27-9292-c7fc80013c0d"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="ordersdeatails",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("5ff007df-5d2b-4c92-a0be-59fda5d8fca3"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("6296cef5-be7e-4c4c-a038-d3cda3d466dd"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("973527ca-e06b-4df9-8dc4-fe14a0469a27"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("5ec4ea75-5886-4d5c-8155-54895bc275f6"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
