# Generated by Django 5.0.6 on 2024-07-27 18:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_app_id_alter_displacedproduct_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("20b57cb4-7b11-4a21-92e8-2ae2e033d85a"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="displacedproduct",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("fcf5a734-5de5-4a46-b788-78588cbd51be"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b5071194-bdcb-4e05-8323-2fb419fd90d3"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="ordersdeatails",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("f43ee897-570b-4cf4-af58-fcaf69a16e39"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("a6a9d234-b41c-4be6-9629-3365a51aec07"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("ae100ffd-d936-4a7f-94aa-c4231daea236"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("2e6b5e1b-c205-4680-95d0-62855cad0208"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
