# Generated by Django 5.0.6 on 2024-07-27 18:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_app_id_alter_displacedproduct_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("c8e36af3-431c-41cb-a236-7e17fcb07f90"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="displacedproduct",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("be943777-a5a9-497d-969f-4506efb87a58"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("62d85e61-8119-40ae-8d30-050274fc8fb5"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="ordersdeatails",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("540034ba-3d35-4522-b346-555777d65948"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="ordersdeatails",
            name="product_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.product"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("3215ae38-4191-4376-a4ad-6dbc8dd21a15"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("1d46bb85-2eb6-4d49-b26e-44ea337301e4"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("353c8c09-219a-45d5-95ac-2bf9acd57e08"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
