# Generated by Django 5.0.6 on 2024-08-01 17:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_remove_product_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="unit_in_stock",
            new_name="quantity_in_stock",
        ),
        migrations.RemoveField(
            model_name="product",
            name="unit_on_order",
        ),
    ]
