# Generated by Django 5.0.6 on 2024-08-01 18:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_rename_unit_in_stock_product_quantity_in_stock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="date_added",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
