# Generated by Django 5.0.6 on 2024-08-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
        ),
    ]
