# Generated by Django 5.0.6 on 2024-08-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_shelf"),
    ]

    operations = [
        migrations.AddField(
            model_name="shelf",
            name="location",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
