# Generated by Django 5.0.6 on 2024-08-30 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_alter_shelf_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="shelf",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.shelf",
            ),
        ),
    ]
