# Generated by Django 5.0.6 on 2024-08-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_shelf_datetime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shelf",
            name="datetime",
        ),
        migrations.AddField(
            model_name="shelf",
            name="close_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shelf",
            name="open_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
